# Generated by Django 5.2 on 2025-04-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('release_year', models.IntegerField(verbose_name='Год начала выпуска')),
                ('graduation_year', models.IntegerField(verbose_name='Год окончания выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cr_app.car', verbose_name='Автомобиль')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='cr_app.country', verbose_name='Страна')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='cr_app.manufacturer', verbose_name='Производитель'),
        ),
    ]
